# Generated by Django 6.0.1 on 2026-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
