# Generated by Django 6.0.1 on 2026-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_id_alter_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(default='', max_length=25),
        ),
    ]
