# Generated by Django 6.0.1 on 2026-03-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_cpu_brand_client_disk_size_client_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cpu_brand',
        ),
        migrations.RemoveField(
            model_name='client',
            name='disk_size',
        ),
        migrations.RemoveField(
            model_name='client',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='client',
            name='platform',
        ),
    ]
